# Generated by Django 4.1.7 on 2023-03-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarAppointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='megrendelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('telefonszam', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
