# Generated by Django 4.1.7 on 2023-03-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarAppointment', '0002_megrendelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megrendelo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adja meg a email cimét!'),
        ),
        migrations.AlterField(
            model_name='megrendelo',
            name='telefonszam',
            field=models.IntegerField(verbose_name='Adja meg a telefonszámát!'),
        ),
    ]
