# Generated by Django 4.1.7 on 2023-03-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarAppointment', '0003_alter_megrendelo_email_alter_megrendelo_telefonszam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megrendelo',
            name='nev',
            field=models.CharField(max_length=100, verbose_name='Adja meg a teljes nevét!'),
        ),
    ]
