# Generated by Django 4.1.7 on 2023-03-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarAppointment', '0004_alter_megrendelo_nev'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
