# Generated by Django 4.1.7 on 2023-03-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarAppointment', '0005_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megrendelo',
            name='telefonszam',
            field=models.IntegerField(verbose_name='Adja meg a telefonszámot!'),
        ),
    ]
