# Generated by Django 4.1.7 on 2023-03-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarAppointment', '0006_alter_megrendelo_telefonszam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megrendelo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='megrendelo',
            name='telefonszam',
        ),
    ]
