# Generated by Django 4.1.7 on 2023-03-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarAppointment', '0007_remove_megrendelo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='megrendelo',
            name='telefonszam',
            field=models.CharField(default=1, max_length=11, verbose_name='Adja meg a telefonszámot!'),
            preserve_default=False,
        ),
    ]
