# Generated by Django 4.1.7 on 2023-03-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarAppointment', '0008_megrendelo_telefonszam'),
    ]

    operations = [
        migrations.AddField(
            model_name='megrendelo',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Adja meg a email cimét!'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='megrendelo',
            name='telefonszam',
            field=models.IntegerField(verbose_name='Adja meg a telefonszámot!'),
        ),
    ]
