# Generated by Django 4.1.7 on 2023-03-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarAppointment', '0009_megrendelo_email_alter_megrendelo_telefonszam'),
    ]

    operations = [
        migrations.AddField(
            model_name='megrendelo',
            name='datum',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='megrendelo',
            name='telefonszam',
            field=models.CharField(max_length=11, verbose_name='Adja meg a telefonszámot!'),
        ),
    ]
