# Generated by Django 4.1.7 on 2023-03-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarAppointment', '0010_megrendelo_datum_alter_megrendelo_telefonszam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megrendelo',
            name='datum',
        ),
    ]
